language: rust
rust:
  - stable
  - nightly
  - beta
matrix:
  fast_finish: true
  allow_failures:
    - rust: beta
    - rust: stable

before_install:
  - sudo apt-get -qq update

after_success: |
  sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev &&
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xvf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build &&
  cmake .. && sudo make install && cd ../.. &&
  kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/logmap
